### ISSUE TITLE
Capstone Milestones

### ISSUE THREAD

**Issue by goodonefrankie** [PointAndTranslateDevTeam/point-translate#1]
**Wednesday:** 
- [x] MVP Statements

**Thursday:**
- [x] Team Contract
- [x] Github Org (add instructors and pin to slack)
- [x] Break down MVP into individual tasks on Kanban board (GitHub Projects)

**Friday:**
- [x] Wireframes (optional)
- [x] Tech Stack/Libraries

**Monday:**
- [ ] Proof of Concept
